/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

/**
 *
 * @author Bryan Paz Ramirez
 */
public class Arbol extends javax.swing.JPanel {

    /**
     * Creates new form Arbol
     */
    public Arbol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtDato7 = new javax.swing.JTextField();
        TxtDato1 = new javax.swing.JTextField();
        TxtDato2 = new javax.swing.JTextField();
        TxtDato3 = new javax.swing.JTextField();
        TxtDato6 = new javax.swing.JTextField();
        TxtDato5 = new javax.swing.JTextField();
        TxtDato4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LbTotal = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(TxtDato7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 70, 70));
        add(TxtDato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 70, 70));
        add(TxtDato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, 70));
        add(TxtDato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 70, 70));
        add(TxtDato6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 70, 70));
        add(TxtDato5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 70, 70));
        add(TxtDato4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 70, 70));

        jButton1.setText("Sumar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel1.setText("Total");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        LbTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        add(LbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 100, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbTotal;
    private javax.swing.JTextField TxtDato1;
    private javax.swing.JTextField TxtDato2;
    private javax.swing.JTextField TxtDato3;
    private javax.swing.JTextField TxtDato4;
    private javax.swing.JTextField TxtDato5;
    private javax.swing.JTextField TxtDato6;
    private javax.swing.JTextField TxtDato7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
