/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Conexion.Consultas;
import p1bryanpaz.DatosAlumno;

    
public class Editar extends javax.swing.JFrame {

    String Id;
    String Carne;
    String Nombre;
    String Curso;
    public Editar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbCurso = new javax.swing.JLabel();
        MostrarId = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        MostrarNombre = new javax.swing.JTextField();
        MostrarCarne = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        LbCarne = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        LbId = new javax.swing.JLabel();
        MostrarCurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbCurso.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LbCurso.setText("Curso:");
        getContentPane().add(LbCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        MostrarId.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        MostrarId.setText("Id:");
        getContentPane().add(MostrarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        LbNombre.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LbNombre.setText("Nombre:");
        getContentPane().add(LbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        MostrarNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        MostrarNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(MostrarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 300, 40));

        MostrarCarne.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        MostrarCarne.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(MostrarCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 300, 40));

        BtnBuscar.setText("Buscar");
        BtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBuscarMouseClicked(evt);
            }
        });
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 110, 50));

        LbCarne.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LbCarne.setText("Carne:");
        getContentPane().add(LbCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        TxtBuscar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TxtBuscar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 130, 40));

        jButton2.setText("Actualizar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 110, 50));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setText("Buscar Por Id:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        LbId.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LbId.setText("Id:");
        getContentPane().add(LbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        MostrarCurso.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        MostrarCurso.setText("Curso");
        getContentPane().add(MostrarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBuscarMouseClicked
        int Dato = Integer.parseInt(TxtBuscar.getText());
        DatosAlumno Estudiante = new DatosAlumno();
        
        Consultas enviar = new Consultas();
        enviar.Buscar(Dato);
        
    }//GEN-LAST:event_BtnBuscarMouseClicked

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void edit(DatosAlumno Estudiante){
        MostrarId.setText(String.valueOf(Estudiante.getId()));
        MostrarCarne.setText(Estudiante.getCarne());
        MostrarNombre.setText(Estudiante.getNombre());
        MostrarCurso.setText(Estudiante.getCurso());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JLabel LbCarne;
    private javax.swing.JLabel LbCurso;
    private javax.swing.JLabel LbId;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JTextField MostrarCarne;
    private javax.swing.JLabel MostrarCurso;
    private javax.swing.JLabel MostrarId;
    private javax.swing.JTextField MostrarNombre;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
