/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Conexion.Consultas;
import javax.swing.JOptionPane;
import p1bryanpaz.DatosAlumno;

/**
 *
 * @author Bryan Paz Ramirez
 */
public class GuardarRegistros extends javax.swing.JPanel {

    /**
     * Creates new form GuardarRegistros
     */
    public GuardarRegistros() {
        initComponents();
        insertarDatos();
    }
    
    public void insertarDatos(){
        CmbCurso.addItem("Programacion III");
        CmbCurso.addItem("Emprendedores De Negocios");
        CmbCurso.addItem("Metodos Numericos");
        CmbCurso.addItem("Estadistica II");
        CmbCurso.addItem("Electronica Analogica");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtCarne = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CmbCurso = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Curso:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setText("Carne:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setText("Nombre:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        TxtNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TxtNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 300, 40));

        TxtCarne.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TxtCarne.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        add(TxtCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 300, 40));

        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 110, 50));

        add(CmbCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 160, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DatosAlumno Alumno = new DatosAlumno();
        Alumno.setCarne(TxtCarne.getText());
        Alumno.setNombre(TxtNombre.getText());
        Alumno.setCurso((String) CmbCurso.getSelectedItem());
        
        if(!(Alumno.getCarne().equals("") && Alumno.getNombre().equals(""))){
            Consultas datos = new Consultas();
            datos.Guardar(Alumno);
        }else{
            JOptionPane.showMessageDialog(null, "Llene cada uno de los campos", "Advertencia", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbCurso;
    private javax.swing.JTextField TxtCarne;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
